### ISSUE TITLE
Not compatible with Corda v3 and v3.1

### ISSUE THREAD

**Issue by marioschlipf** [corda/corda-ansible#13]
Since Corda v3, the versionId of Corda seems to be a bit weird in Maven Central: https://mvnrepository.com/artifact/net.corda/corda

For Corda v2 it looks like this:
```
    <groupId>net.corda</groupId>
    <artifactId>corda</artifactId>
    <version>2.0.0</version>
```

Corda v3.0:
```
    <groupId>net.corda</groupId>
    <artifactId>corda</artifactId>
    <version>corda-3.0</version>
```

Corda v3.1:
```
    <groupId>net.corda</groupId>
    <artifactId>corda</artifactId>
    <version>3.1-corda</version>
```

The ansible task looks like this (truncated):
```
- name: Get corda jars from Maven Central
  maven_artifact: group_id=net.corda artifact_id={{ item }} version={{ corda_version }}-corda extension=jar dest={{ corda_dir_location }}/{{ item }}.jar repository_url='http://repo1.maven.org/maven2'
  with_items:
    - corda
    - corda-webserver
```

It is not able to download the Corda jars for version 3+.

Is that change of versionId scheme intentional?
